{{- $ca := genCA .Values.ca.name (int .Values.ca.lifetime) }}
{{- $server := genSignedCert .Values.server.name .Values.server.subjectAlternativeName.ip .Values.server.subjectAlternativeName.dns (int .Values.server.lifetime) $ca -}}

apiVersion: v1
kind: Secret
metadata:
  name: certs
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  caCert: {{ $ca.Cert | b64enc | quote }}
  serverCert: {{ $server.Cert | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: server-key
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  key: {{ $server.Key | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: ca-key
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  key: {{ $ca.Key | b64enc | quote }}
